
apiVersion: v1
kind: Service
metadata:
  name: database-mysql-service
spec:
  type: ClusterIP
  selector:
    app: database-mysql-deployment
  ports:
    - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment
  ports:
    - port: 80